/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-06-17

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
uint32_t * RCCADOR= 0x40021000 + 0x14;
volatile uint32_t PA0Pressed;

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

void initGPIO(void){
	//enabling RCC for port
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	//setting ports to output mode
	GPIOC->MODER |= GPIO_MODER_MODER8_0;
	GPIOC->MODER |= GPIO_MODER_MODER9_0;
	//setting push button
	GPIOA->MODER &= ~GPIO_MODER_MODER0;


	GPIOA -> PUPDR |= GPIO_PUPDR_PUPDR0_1; //Enable PA0's pull down resistor.
	GPIOA -> MODER &= ~GPIO_MODER_MODER0;

	//Turning off the LED
	//GPIOC->ODR |= GPIO_ODR_8;
	//GPIOC->ODR |= GPIO_ODR_9;

 }

void blinky(){
	for(;;){
			GPIOC->ODR |= GPIO_ODR_9;
			GPIOC->ODR &= ~GPIO_ODR_8;
			delay();
			GPIOC->ODR &= ~GPIO_ODR_9;
			GPIOC->ODR |= GPIO_ODR_8;
			delay();
	}


}

void delay(void){
	for(volatile int i=0;i<100000;i++){

	}
}

int main(void)
{
	*RCCADOR |= 0b1 << 18*RCCADOR |= 0b1 << 18;
	initGPIO();
	for(;;){
		PA0Pressed = ((GPIOA -> IDR & GPIO_IDR_0)!=0);
		if(PA0Pressed){
			blinky();
		}
	}// Loop forever;
	initGPIO();
	for(;;){
		PA0Pressed = ((GPIOA -> IDR & GPIO_IDR_0)!=0);
		if(PA0Pressed){
			blinky();
		}
	}// Loop forever


}
